kind: Workflow
apiVersion: argoproj.io/v1alpha1
metadata:
  name: catalogue-container-kill
  namespace: litmus
  labels:
    subject: sock-shop_kube-proxy
    workflows.argoproj.io/controller-instanceid: f21787ba-08ee-4649-ab66-c880492636dc
spec:
  templates:
    - name: argowf-chaos
      inputs: {}
      outputs: {}
      metadata: {}
      steps:
        - - name: install-chaos-faults
            template: install-chaos-faults
            arguments: {}
        - - name: run-chaos
            template: run-chaos
            arguments: {}
        - - name: cleanup-chaos-resources
            template: cleanup-chaos-resources
            arguments: {}
    - name: install-chaos-faults
      inputs:
        artifacts:
          - name: install-chaos-faults
            path: /tmp/container-kill.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Kills a container belonging to an application pod
                kind: ChaosExperiment
                metadata:
                  name: container-kill
                  labels:
                    name: container-kill
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups: [""]
                        resources: ["pods"]
                        verbs: ["create","delete","get","list","patch","update","deletecollection"]
                      - apiGroups: [""]
                        resources: ["events"]
                        verbs: ["create","get","list","patch","update"]
                      - apiGroups: [""]
                        resources: ["configmaps"]
                        verbs: ["get","list"]
                      - apiGroups: [""]
                        resources: ["pods/log"]
                        verbs: ["get","list","watch"]
                      - apiGroups: [""]
                        resources: ["pods/exec"]
                        verbs: ["get","list","create"]
                      - apiGroups: ["apps"]
                        resources: ["deployments","statefulsets","replicasets","daemonsets"]
                        verbs: ["list","get"]
                      - apiGroups: ["batch"]
                        resources: ["jobs"]
                        verbs: ["create","list","get","delete","deletecollection"]
                      - apiGroups: ["litmuschaos.io"]
                        resources: ["chaosengines","chaosexperiments","chaosresults"]
                        verbs: ["create","list","get","patch","update","delete"]
                    image: "litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.28.0"
                    imagePullPolicy: Always
                    args:
                    - -c
                    - ./experiments -name container-kill
                    command:
                    - /bin/bash
                    env:
                    - name: TARGET_CONTAINER
                      value: ''
                    - name: RAMP_TIME
                      value: ''
                    - name: TARGET_PODS
                      value: ''
                    - name: CHAOS_INTERVAL
                      value: '10'
                    - name: SIGNAL
                      value: 'SIGKILL'
                    - name: SOCKET_PATH
                      value: '/var/run/docker.sock'
                    - name: CONTAINER_RUNTIME
                      value: 'docker'
                    - name: TOTAL_CHAOS_DURATION
                      value: '20'
                    - name: PODS_AFFECTED_PERC
                      value: ''
                    - name: DEFAULT_HEALTH_CHECK
                      value: 'false'
                    - name: LIB_IMAGE
                      value: 'litmuschaos.docker.scarf.sh/litmuschaos/go-runner:3.28.0'
                    - name: SEQUENCE
                      value: 'parallel'
                    labels:
                      name: container-kill
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl apply -f /tmp/container-kill.yaml -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
    - name: run-chaos
      inputs:
        artifacts:
          - name: run-chaos
            path: /tmp/chaosengine-run-chaos.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    context: sock-shop_kube-proxy
                    workflow_run_id: "{{ workflow.uid }}"
                    workflow_name: catalogue-container-kill
                  generateName: run-chaos
                spec:
                  appinfo:
                    appns: sock-shop
                    applabel: name=catalogue
                    appkind: deployment
                  jobCleanUpPolicy: retain
                  engineState: active
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: container-kill
                      spec:
                        components:
                          env:
                            - name: TARGET_CONTAINER
                              value: catalogue
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: TOTAL_CHAOS_DURATION
                              value: "20"
                            - name: SIGNAL
                              value: SIGKILL
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
      outputs: {}
      metadata:
        labels:
          weight: "10"
      container:
        name: ""
        image: litmuschaos/litmus-checker:2.11.0
        args:
          - -file=/tmp/chaosengine-run-chaos.yaml
          - -saveName=/tmp/engine-name
        resources: {}
    - name: cleanup-chaos-resources
      inputs: {}
      outputs: {}
      metadata: {}
      container:
        name: ""
        image: litmuschaos/k8s:latest
        command:
          - sh
          - -c
        args:
          - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
            {{workflow.parameters.adminModeNamespace}}
        resources: {}
  entrypoint: argowf-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
      - name: appNamespace
        value: sock-shop
  serviceAccountName: argo-chaos
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
status: {}
