apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-v3-configmap
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs: []
