apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-v3
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-v3
  template:
    metadata:
      labels:
        app: prometheus-v3
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v3.2.1
        args:
        - '--storage.tsdb.retention.time=360h'
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--web.enable-remote-write-receiver'
        ports:
        - name: web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-v3-configmap
      nodeSelector:
        beta.kubernetes.io/os: linux
