apiVersion: v1
kind: Service
metadata:
  name: prometheus-v3
  namespace: monitoring
spec:
  selector:
    app: prometheus-v3
  type: NodePort
  ports:
  - name: web
    port: 9090
    targetPort: 9090
    nodePort: 31091
