{
 "title": "SockShop Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Métricas de Ouro",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Tráfego",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% de Erros",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "(100* sum(rate(request_duration_seconds_count{status_code=~\"5..\"}[5m])) by (name) / sum(rate(request_duration_seconds_count[5m])) by (name)) or 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo médio Requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_sum{route!~\"health|metrics\"}[5m])) by (name)/sum(rate(request_duration_seconds_count{route!~\"health|metrics\"}[5m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência P95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (le, name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"sock-shop\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_memory_usage_bytes{namespace=\"sock-shop\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_fs_writes_bytes_total{namespace=\"sock-shop\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KPIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Disponibilidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(1 - (sum(rate(request_duration_seconds_count{status_code=~\"5..\"}[5m])) by (name) / sum(rate(request_duration_seconds_count[5m])) by (name))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concorrência",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_seconds_count[5m])) by (name) * histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (le, name))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "MongoDB Avg Ops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opLatencies_ops[5m])) by (name, op_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Avg Ops Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(mongodb_ss_opLatencies_latency[5m])) by (name, op_type) / sum(rate(mongodb_ss_opLatencies_ops[5m])) by (name, op_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mysql Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Commands Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(redis_commands_processed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } }
 ]
}